Update Sentry requirement to ~> 5
This is required to make the pod build with Xcode 12.2, otherwise we'd
get the following error:

> xcodebuild:
>   Sentry/Sources/SentryCrash/Recording/Tools/SentryCrashObjC.c:198:54:
>     error: use of undeclared identifier 'kCFCoreFoundationVersionNumber_iOS_8_x_Max'